DROP EXTENSION IF EXISTS pg_cron;
DROP EXTENSION IF EXISTS pg_net;
DROP SCHEMA IF EXISTS cron CASCADE;
DROP SCHEMA IF EXISTS net CASCADE;
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION pg_cron WITH SCHEMA extensions;
CREATE EXTENSION pg_net WITH SCHEMA extensions;